# Generated by Django 4.0.5 on 2022-08-09 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contacts',
            new_name='contact',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='textarea',
            new_name='password',
        ),
    ]
