# Generated by Django 4.0.5 on 2022-08-09 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_contact_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='email',
            field=models.CharField(default='ok@', max_length=122),
        ),
    ]
